### ISSUE TITLE
Attempting to queue un-embeddable videos results in an error

### ISSUE THREAD

**Issue by Klocko** [joelamos/SourceRadio#12]
java.lang.RuntimeException: ERROR: Signature extraction failed: Traceback (most recent call last):
at com.joelchristophel.sourceradio.Song.createSong(Song.java:169)
at com.joelchristophel.sourceradio.Playlist.handleNewInput(Playlist.java:226)
at com.joelchristophel.sourceradio.LogReader$1.run(LogReader.java:96)
at java.lang.Thread.run(Unknown Source)

This means that you cannot put videos such as Rick Astley - Never Gonna Give You Up in the queue.

**Comment by joelamos** [comment]
I'm unsure what you mean by un-embeddable videos, but I can ensure you that Never Gonna Give You Up is one of my most-requested songs.

This issue occurs when YouTube changes its website structure and youtube-dl hasn't caught up yet. Thankfully, I just added the feature that auto-updates youtube-dl whenever you run SourceRadio. Since the extraction issue was fixed with [youtube-dl 2017.01.31](https://github.com/rg3/youtube-dl/releases/tag/2017.01.31), all you need to do is re-run SourceRadio.

**Comment by joelamos** [comment]
Commit f498d68 adds a useful error message for when this occurs.
