### ISSUE TITLE
SourceRadio wont recognize me as admin

### ISSUE THREAD

**Issue by whofam** [joelamos/SourceRadio#6]
i cannot skip or everything else, even tried to put my steam id3, nothing worked, i can play songs fine but i can't stop or skip them, all the commands wont work

**Comment by joelamos** [comment]
Thanks for reporting this. Could you post what your steamID3 line looks like in properties.txt?

**Comment by whofam** [comment]
steamid3 -> 93882472
original one [U:1:93882472]

inside userdata there are two folders, one with my id3 and another one that is my alt; the number on the first folder it's the same as my id3

**Comment by joelamos** [comment]
Does this behavior happen on all types of servers (e.g. casual, community, competitive)? If not, which have you been playing on?

Do you have the file `Steam\userdata\93882472\config\localconfig.vdf`? If so, could you post yours?

As a temporary fix, your commands should be recognized as privileged if you enter them via the game console. When entering commands into the console, you must use underscores instead of spaces. Also, you could change your binds in `sourceradio.cfg` to issue the commands via the console rather than chat. Note, though, that the binds are re-written when the program is restarted.

Example: `bind o "say_team !skip"` would simply become `bind o !skip`

**Comment by whofam** [comment]
there

**Comment by whofam** [comment]
[localconfig.zip](https://github.com/joelamos/SourceRadio/files/386661/localconfig.zip)

**Comment by joelamos** [comment]
Thanks for the file. I didn't see anything unusual there. Also, you never answered my question about the types of servers you've tried.

Some other things that could be helpful:
- Type `status` into the console and post the output.
- Go into the `tf` directory (or whatever game you're playing) and find either the file `console.log` or `console2.log` and post it.

**Comment by whofam** [comment]
[console and status.txt](https://github.com/joelamos/SourceRadio/files/387267/console.and.status.txt)

there

**Comment by joelamos** [comment]
Whenever you type a message in chat, it appears as `(SQUADRA) who fam` rather than just `who fam`. This is why you're not being recognized as an admin. Can you explain what `SQUADRA` is?

**Comment by whofam** [comment]
squadra means team in italian, maybe that's why it does not recognize the commands

**Comment by joelamos** [comment]
Wow, I'd never considered that TF2 is available in multiple languages.

I'll add multi-language support in the next update. 

For now, you can use chat to issue commands as long as it's not team chat.

**Comment by joelamos** [comment]
Commit 6cddc1e should fix this issue.
